---
title: "clean-police"
author: "Elinor chu"
date: "11/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) 
library(stringr)
```

```{r}
file = "../data/raw/scorecard.csv"
scorecard_raw = read_csv(file)
scorecard_raw = scorecard_raw %>% select("fips_state_code", "fips_county_code",
                                         "calc_police_violence_score","calc_police_accountability_score",
                                         "calc_approach_to_policing_score","calc_police_funding_score")
```

```{r}


scorecard_raw = data.frame(sapply(scorecard_raw, function(x) as.numeric(gsub("%", "", x)))) %>%
  rename(police_violence_score = calc_police_violence_score, 
         police_accountability_score=calc_police_accountability_score, 
         approach_to_policing_score = calc_approach_to_policing_score, 
         police_funding_score = calc_police_funding_score) %>% 
  mutate(fips_state_code=as.character(fips_state_code), fips_county_code = as.character(fips_county_code))

scorecard_raw$fips_county_code = str_pad(scorecard_raw$fips_county_code, 3, pad = "0")

scorecard_raw$fips = str_c(scorecard_raw$fips_state_code, scorecard_raw$fips_county_code)

scorecard_raw = scorecard_raw %>% select(-fips_state_code,-fips_county_code) %>% mutate(fips = as.numeric(fips))


```

