---
title: "EDA"
author: "Elinor chu"
date: "12/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(lubridate)
library(tidyverse)
library(ggplot2)
library(readr)
library(readxl)
library(usdata)
library(tm)
library(stringr)


library(kableExtra)
```

```{r}
theft_train=read_csv("/Users/diyangchu/Documents/2-grad@Penn/STAT471/theft-crime-2020/data/clean/theft_train.csv")
```

```{r}
ggplot(aes(x = theftrate)) +
  geom_histogram()+
  labs(y = "Count", 
       x = "Theft Rate",
       title = "Histogram of Theft Rate")+
  theme_bw()+
  scale_y_log10()
```

```{r}
theft_train %>% select(-fips, -state, -county) %>%
ggplot(aes(y=theftrate)) +
  geom_boxplot()+
  labs(y = "Theft Rate",
       title = "Boxplot of Theft Rate")+
  theme_bw()
```

```{r}
theft_train %>% select(state,county,theftrate) %>% arrange(desc(theftrate)) %>% head(10) %>%
  kable(format = "latex", row.names = NA, 
        booktabs = TRUE,
        digits = 3,
        col.names = c("State", "County","Theft Rate"),
        caption = "This a table showing the top 10 counties with the highest theft rate.") %>%
  kable_styling(position = "center") %>%
  kable_styling(latex_options = "HOLD_position")
```

#EDA for important features


```{r}
# plot theftrate against poor_fair_health
p1 = theft_train %>% select(-fips, -state, -county) %>% 
  ggplot(aes(x = poor_fair_health, y = theftrate)) +
  geom_point(alpha = 0.6) + 
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = "lm", formula = "y~x", se = FALSE) +
  labs(x = "Percent adults reporting poor or fair health", 
       y = "Theft Rate",
       title = "Percentage of Adults Reporting\n Fair or Poor Health vs Theft Rate") +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
theft_train %>% arrange(desc(poor_fair_health))%>%head(5)
```



```{r}
# plot theftrate against housing_density
p2 = theft_train %>% select(-fips, -state, -county)%>%
  ggplot(aes(x = housing_density, y = theftrate)) +
  geom_point(alpha = 0.6) + 
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = "lm", formula = "y~x", se = FALSE) +
  labs(x = "Housing Density", 
       y = "Theft Rate",
       title = "Housing Density vs Theft Rate") +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
theft_train %>% arrange(desc(housing_density))%>%head(5)
```


```{r}
# plot theftrate against pop_density
p3 = theft_train %>% select(-fips, -state, -county) %>%
  ggplot(aes(x = pop_density, y = theftrate)) +
  geom_point(alpha = 0.6) + 
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = "lm", formula = "y~x", se = FALSE) +
  labs(x = "Population Density", 
       y = "Theft Rate",
       title = "Population Density vs Theft Rate") +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
theft_train %>% arrange(desc(pop_density))%>%head(5)
```


```{r}
# plot theftrate against pertrump
p4 = theft_train %>% select(-fips, -state, -county)%>%
  ggplot(aes(x = pertrump, y = theftrate)) +
  geom_point(alpha = 0.6) + 
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = "lm", formula = "y~x", se = FALSE) +
  labs(x = "Percent of Trump Supporters", 
       y = "Theft Rate",
       title = "Percent of Trump Supporters (in 2020) vs Theft Rate") +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
theft_train %>% arrange(desc(pertrump))%>%head(5)
```


```{r}
# plot theftrate against PctEmpFIRE
p5 = theft_train %>% select(-fips, -state, -county)%>%
  ggplot(aes(x = PctEmpFIRE, y = theftrate)) +
  geom_point(alpha = 0.6) + 
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = "lm", formula = "y~x", se = FALSE) +
  labs(x = "Percent of People Employed in FIRE", 
       y = "Theft Rate",
       title = "Percent of People Employed in \n Finance/Insurance/Real Estate(FIRE) vs Theft Rate") +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
theft_train %>% arrange(desc(PctEmpFIRE))%>%select(state, county, PctEmpFIRE, theftrate)%>%head(5)
```


```{r}
# plot theftrate against saversperpop
p6 = theft_train %>% select(-fips, -state, -county)%>%
  ggplot(aes(x = saversperpop, y = theftrate)) +
  geom_point(alpha = 0.6) + 
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = "lm", formula = "y~x", se = FALSE) +
  labs(x = "saversperpop", 
       y = "Theft Rate",
       title = "saversperpop") +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
theft_train %>% arrange(desc(saversperpop))%>%select(state, county, saversperpop, theftrate)%>%head(5)
```


```{r}
# plot theftrate against unemp_bens_possible
p7 = theft_train %>% select(-fips, -state, -county)%>%
  ggplot(aes(x = unemp_bens_possible, y = theftrate)) +
  geom_point(alpha = 0.6) + 
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = "lm", formula = "y~x", se = FALSE) +
  labs(x = "State unemployment insurance", 
       y = "Theft Rate",
       title = "State Unemployment Insurance vs Theft Rate") +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))
```



```{r}
# plot theftrate against lessthan_hs
p8= theft_train %>% select(-fips, -state, -county)%>%
  ggplot(aes(x = lessthan_hs, y = theftrate)) +
  geom_point(alpha = 0.6) + 
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = "lm", formula = "y~x", se = FALSE) +
  labs(x = "Percent with less than HS education", 
       y = "Theft Rate",
       title = "Percent of people with Less than High School\n Education vs Theft Rate") +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
theft_train %>% arrange(desc(lessthan_hs))%>%select(state, county, lessthan_hs, theftrate)%>%head(5)
```


```{r}
# plot theftrate against PctEmpConstruction
p9= theft_train %>% select(-fips, -state, -county)%>%
  ggplot(aes(x = PctEmpConstruction, y = theftrate)) +
  geom_point(alpha = 0.6) + 
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = "lm", formula = "y~x", se = FALSE) +
  labs(x = "Percent employed in construction", 
       y = "Theft Rate",
       title = "Percent of People Employed in Construction") +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
theft_train %>% arrange(desc(PctEmpConstruction))%>%select(state, county, PctEmpConstruction, theftrate)%>%head(5)
```


