---
title: "Response"
author: "Mason Shihab"
date: "11/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(lubridate)
library(tidyverse)
library(ggplot2)
library(readr)
library(tidycensus)
library(rpart)
library(rpart.plot)
library(ipred)
library(readxl)
library(usdata)
library(tm)
library(stringr)
```


## Response

```{r}
hope = read.csv("https://raw.githubusercontent.com/grammakov/USA-cities-and-states/master/us_cities_states_counties.csv", sep = "|") %>% rename(State = State.full) 
hope = hope %>% select(-City.alias)
countycrime = read_xlsx("../data/raw/countycrime.xlsx") %>% select(State, County, Total_Theft)
citycrime = read_xlsx("../data/raw/citycrime.xlsx") 
```


```{r}
citycrime$State = removeNumbers(citycrime$State)
citycrime$City = removeNumbers(citycrime$City)

countycrime$State = removeNumbers(countycrime$State)
countycrime$County = removeNumbers(countycrime$County)
```


```{r}
countycrime$county_words = sapply(gregexpr("\\S+", countycrime$County), length)


stopwords = c(" County Police Department", " County Unified Police Department", " Public Safety")

countycrime$County = removeWords(countycrime$County, stopwords)

countycrime = countycrime %>% group_by(County, State) %>% summarise(Total_Theft = sum(Total_Theft)) %>% ungroup()

```



```{r}

citycrimecounty = hope %>% inner_join(citycrime, by = c("State", "City")) %>% distinct() 

citycrimecounty$County = tolower(citycrimecounty$County)
citycrimecounty$County = str_to_title(citycrimecounty$County)


sum(filter(citycrimecounty, County == "Franklin" & State == "Ohio")$Population)

```


```{r}
citiestocounties = citycrimecounty %>% group_by(County, State) %>% summarise(Total_Thefts = sum(Total_Thefts))
citiestocounties$County_State = paste(citiestocounties$County, citiestocounties$State)
countycrime$County_State = paste(countycrime$County, countycrime$State)

```

```{r}
missingcounties = citiestocounties %>% filter(!(County_State %in% countycrime$County_State))  %>% rename(Total_Theft = Total_Thefts)
```

```{r}
response = rbind(missingcounties, countycrime) %>% drop_na()
```


```{r}
countycheck = response %>% mutate(countywrd = "County")
countycheck$countytest = paste(countycheck$County, countycheck$countywrd)

missingfromresponse = keyfile %>% filter(!(county %in% countycheck$countytest)) 


```

```{r}
missingfromresponse %>% filter((county %in% incar_0$county))
```